//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CatalogoVideojuegosMVCEntities : DbContext
    {
        public CatalogoVideojuegosMVCEntities()
            : base("name=CatalogoVideojuegosMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Distribuidores> Distribuidores { get; set; }
        public virtual DbSet<Estudios> Estudios { get; set; }
        public virtual DbSet<Generos> Generos { get; set; }
        public virtual DbSet<Juegos> Juegos { get; set; }
        public virtual DbSet<Motores> Motores { get; set; }
        public virtual DbSet<Plataformas> Plataformas { get; set; }
    }
}
